add dashboard + change password
Developpons-Discord/ReviewerApp pull request #5
Opened 2023-08-04 18:55 UTC by Welpike

- add dashboard
- change password feature
- redirect on root (if logged in -> /dasboard, else -> /auth

2023-08-04 20:38 UTC, RedsTom requested changes

2023-08-04 20:38 UTC, RedsTom commented on src/lib/auth/changePassword.ts
> +import axios, { AxiosError } from 'axios';
Le nom des fichiers devrait être en kebab-case

2023-08-04 20:38 UTC, RedsTom commented on src/lib/auth/getCurrentUser.ts
> +import axios, { AxiosError } from 'axios';
Le nom des fichiers devrait être en kebab-case

2023-08-04 20:38 UTC, RedsTom commented on src/routes/auth/ForgotPassword.svelte
> +		const result = await sendEmail(email);
Un nom plus explicite serait meilleur je pense, par exemple `sendResetPasswordEmail` ou quelque chose du genre.

2023-08-04 20:38 UTC, RedsTom commented on src/routes/auth/change-password/+layout.svelte
> +</section>
Nouvelle ligne en fin de fichier manquante

2023-08-04 20:38 UTC, RedsTom commented on src/routes/auth/change-password/+layout.svelte
> +<script>
Le layout du /auth ne s'applique-t-il pas déjà ?

2023-08-04 20:38 UTC, RedsTom commented on src/routes/auth/change-password/ChangePassword.svelte
> +        errors = errors.concat(_errors)
👀

2023-08-04 20:38 UTC, RedsTom commented on src/routes/dashboard/UserInfo.svelte
> +    });
Est ce que ce n'est pas possible de faire cela au niveau du chargement SSR afin qu'il n'y ait aucun chargement côté client là dessus ?

2023-08-04 20:38 UTC, RedsTom commented on src/routes/dashboard/UserInfo.svelte
> +        <p>Vérifié : {userData.verified ? 'Oui' : 'Non'}</p>
Techniquement toujours oui, puisqu'il faudrait une redirection (que je n'ai pas faite) sur la vérification si l'utilisateur est sur le site et que son compte n'est pas vérifié !

2023-08-04 20:38 UTC, RedsTom commented on src/routes/dashboard/UserInfo.svelte
> +    <!-- here add button to change password -->
👍

2023-08-04 20:40 UTC, RedsTom commented
Globalement c'est plutôt très bien, il faudrait juste passer un petit coup de eslint --fix et résoudre les problèmes cités dans la review et ça sera mergeable !

2023-08-04 20:42 UTC, RedsTom requested changes
Oups petit oubli

2023-08-04 20:42 UTC, RedsTom commented on src/lib/auth/changePassword.ts
> +export async function doChangePassword(userId: number, code: string, password: string, confirmPassword: string) {
Ça manque d'un type de retour

2023-08-05 14:23 UTC, Welpike commented on src/routes/dashboard/UserInfo.svelte
> +    });
je sais pas faire ^^' (je suis en train de chercher)

2023-08-05 17:44 UTC, Welpike commented on src/routes/dashboard/UserInfo.svelte
> +    });
cest bon

2023-08-05 19:13 UTC, RedsTom requested changes
Eslint n'a pas fait que du bien au code style 👀

2023-08-05 20:39 UTC, RedsTom requested changes

2023-08-05 20:39 UTC, RedsTom commented on src/lib/auth/change-password.ts
> +import axios, { AxiosError } from 'axios';
Code style foireux

2023-08-05 20:39 UTC, RedsTom commented on src/routes/+page.svelte
> +	import { onMount } from "svelte";
Tabulation en trop

2023-08-05 20:39 UTC, RedsTom commented on src/routes/auth/change-password/ChangePassword.svelte
> +    }
Tabulations foireuses

2023-08-05 20:39 UTC, RedsTom commented on src/routes/dashboard/+page.svelte
> +	export let data
Tabulations foireuses

2023-08-05 20:39 UTC, RedsTom commented on src/routes/dashboard/+page.ts
> +    if(user != undefined){
Code style non respecté

2023-08-06 08:59 UTC, Welpike commented on src/routes/+page.svelte
> +	import { onMount } from "svelte";
![image](https://github.com/Developpons-Discord/ReviewerApp/assets/106405084/80e82ec3-7689-4f53-81b6-5a28bfb5c989)
bizarre

2023-08-06 09:00 UTC, Welpike commented on src/routes/auth/change-password/ChangePassword.svelte
> +    }
![image](https://github.com/Developpons-Discord/ReviewerApp/assets/106405084/a89fb768-39da-440b-a875-5c723346746a)
same

2023-08-06 09:01 UTC, Welpike commented on src/routes/dashboard/+page.svelte
> +	export let data
![image](https://github.com/Developpons-Discord/ReviewerApp/assets/106405084/1f12405f-6bf8-4fac-b40b-6562143d3cb2)

2023-08-06 09:03 UTC, Welpike commented on src/routes/dashboard/+page.ts
> +    if(user != undefined){
cest mieux ca? `export async function load() {
    const user = await getCurrentUser()
    let userData = user.value
    
    return {
        userData
    }
}`

2023-08-06 11:20 UTC, Welpike commented
sorry for the 4 commits ^^'

2023-08-06 13:05 UTC, RedsTom commented
Pas de problème

2023-08-06 13:07 UTC, RedsTom requested changes

2023-08-06 13:07 UTC, RedsTom commented on src/lib/auth/change-password.ts
> +import axios, {AxiosError} from 'axios';
Toujours pas pour ce fichier

2023-08-06 20:20 UTC, RedsTom approved these changes

2023-08-06 20:20 UTC, merged